l=int(input("Enter the length:"))
b=int(input("Enter the breadth:"))
area=l*b
perimeter=2* (l+b)
print(area)
print(perimeter)

l=int(input("Enter the length:"))
b=int(input("Enter the breadth:"))
area=l*b
perimeter=2* (l+b)
print(area)
print(perimeter)

l=int(input("Enter the length:"))
b=int(input("Enter the breadth:"))
area=l*b
perimeter=2* (l+b)
print(area)
print(perimeter)

l=int(input("Enter the length:"))
b=int(input("Enter the breadth:"))
area=l*b
perimeter=2* (l+b)
print(area)
print(perimeter)

l=int(input("Enter the length:"))
b=int(input("Enter the breadth:"))
area=l*b
perimeter=2* (l+b)
print(area)
print(perimeter)